CREATE TABLE IF NOT EXISTS public.awarding_data
(
    contract_transaction_unique_key character varying(255) COLLATE pg_catalog."default",
    contract_award_unique_key character varying(255) COLLATE pg_catalog."default",
    award_id_piid character varying(255) COLLATE pg_catalog."default",
    modification_number character varying(255) COLLATE pg_catalog."default",
    transaction_number character varying(255) COLLATE pg_catalog."default",
    parent_award_agency_id character varying(255) COLLATE pg_catalog."default",
    parent_award_agency_name character varying(255) COLLATE pg_catalog."default",
    parent_award_id_piid character varying(255) COLLATE pg_catalog."default",
    parent_award_modification_number character varying(255) COLLATE pg_catalog."default",
    federal_action_obligation numeric,
    total_dollars_obligated numeric,
    total_outlayed_amount_for_overall_award numeric,
    base_and_exercised_options_value numeric,
    current_total_value_of_award numeric,
    base_and_all_options_value numeric,
    potential_total_value_of_award numeric,
    disaster_emergency_fund_codes_for_overall_award character varying(255) COLLATE pg_catalog."default",
    outlayed_amount_from_covid19_supplementals_for_overall_award numeric,
    obligated_amount_from_covid19_supplementals_for_overall_award numeric,
    outlayed_amount_from_iija_supplemental_for_overall_award numeric,
    obligated_amount_from_iija_supplemental_for_overall_award numeric,
    action_date date,
    action_date_fiscal_year character varying(255) COLLATE pg_catalog."default",
    period_of_performance_start_date date,
    period_of_performance_current_end_date date,
    period_of_performance_potential_end_date timestamp without time zone,
    ordering_period_end_date date,
    solicitation_date date,
    awarding_agency_code integer,
    awarding_agency_name character varying(255) COLLATE pg_catalog."default",
    awarding_sub_agency_code character varying(255) COLLATE pg_catalog."default",
    awarding_sub_agency_name character varying(255) COLLATE pg_catalog."default",
    awarding_office_code character varying(255) COLLATE pg_catalog."default",
    awarding_office_name character varying(255) COLLATE pg_catalog."default",
    funding_agency_code integer,
    funding_agency_name character varying(255) COLLATE pg_catalog."default",
    funding_sub_agency_code character varying(255) COLLATE pg_catalog."default",
    funding_sub_agency_name character varying(255) COLLATE pg_catalog."default",
    funding_office_code character varying(255) COLLATE pg_catalog."default",
    funding_office_name character varying(255) COLLATE pg_catalog."default",
    treasury_accounts_funding_this_award character varying(255) COLLATE pg_catalog."default",
    federal_accounts_funding_this_award character varying(255) COLLATE pg_catalog."default",
    object_classes_funding_this_award character varying(255) COLLATE pg_catalog."default",
    program_activities_funding_this_award character varying(255) COLLATE pg_catalog."default",
    foreign_funding character varying(255) COLLATE pg_catalog."default",
    foreign_funding_description character varying(255) COLLATE pg_catalog."default",
    sam_exception numeric,
    sam_exception_description character varying(255) COLLATE pg_catalog."default"
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.awarding_data
    OWNER to postgres;